### PR TITLE
Revert "ateucher/frequency-data to master"

### PR DESCRIPTION
**Pull request by sebpardo**
Reverts ateucher/rebird#3

### CODE REVIEW

**Comment by sebpardo** [comment]
I wonder if doing this will get rid of the mess I made with the merging in my old fork...

**Comment by sebpardo** [comment]
I wonder if doing this will get rid of the mess I made with the merging in my old fork into your fork...

**Comment by sebpardo** [comment]
It did! Yay!

Sorry for the mess I made, slowly learning more about improving workflow.

I think it's definitely better to work together on a single fork.

**Comment by ateucher** [comment]
No worries - I make messes all the time :)

**Pull request merged**
