### PR TITLE
Frequencies WIP

### PR DESCRIPTION
**Pull request by sebpardo**
I've improved the function so that it works for querying states and hotspots as well as counties, added an option to output data in wide format, made tidyr a required import in rebird, and wrote a backbone of the help info.

Three things that I think need to be worked on:
- proper checking of input strings so that function stops if `loc` are not provided correctly for each `loctype` (`stop_for_status` doesn't work).
- explaining more clearly how to find the county and hotspot codes in the eBird website.
- Do you think it would be better to add default values for starting and ending years and months?

I am still learning how to write neat code, so if there are any lines that are better coded differently, I would love to see your way of doing it.

### CODE REVIEW

**Comment by ateucher** [comment]
Looks great!!

**Comment by ateucher** [comment]
I like your suggested defaults for start and end years and months.

For checking `loc/loctype` would be nice to be able to access a list of codes... I wonder if the eBird API has that?

**Comment by sebpardo** [comment]
I think there might be a way through the API: https://confluence.cornell.edu/display/CLOISAPI/eBird-1.1-RegionCodeReference

I will edit the defaults once I figure how to set up git to push directly to your repo...

**Comment by ateucher** [comment]
Great. You can just PR if you want (I'll merge faster than last time) -
makes code review easier that way anyway.

**Comment by ateucher** [comment]
Here's the correct API reference: https://confluence.cornell.edu/display/CLOISAPI/eBird-1.1-LocationReference

**Pull request merged**
